// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

`timescale 1ns/1ps
module sha1_control_AXILiteS_s_axi
#(parameter
    C_S_AXI_ADDR_WIDTH = 6,
    C_S_AXI_DATA_WIDTH = 32
)(
    // axi4 lite slave signals
    input  wire                          ACLK,
    input  wire                          ARESET,
    input  wire                          ACLK_EN,
    input  wire [C_S_AXI_ADDR_WIDTH-1:0] AWADDR,
    input  wire                          AWVALID,
    output wire                          AWREADY,
    input  wire [C_S_AXI_DATA_WIDTH-1:0] WDATA,
    input  wire [C_S_AXI_DATA_WIDTH/8-1:0] WSTRB,
    input  wire                          WVALID,
    output wire                          WREADY,
    output wire [1:0]                    BRESP,
    output wire                          BVALID,
    input  wire                          BREADY,
    input  wire [C_S_AXI_ADDR_WIDTH-1:0] ARADDR,
    input  wire                          ARVALID,
    output wire                          ARREADY,
    output wire [C_S_AXI_DATA_WIDTH-1:0] RDATA,
    output wire [1:0]                    RRESP,
    output wire                          RVALID,
    input  wire                          RREADY,
    // user signals
    output wire [0:0]                    i_cs,
    output wire [0:0]                    i_we,
    output wire [7:0]                    i_address,
    output wire [31:0]                   i_write,
    input  wire [31:0]                   o_read,
    input  wire                          o_read_ap_vld,
    input  wire [0:0]                    o_error,
    input  wire                          o_error_ap_vld
);
//------------------------Address Info-------------------
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of i_cs
//        bit 0  - i_cs[0] (Read/Write)
//        others - reserved
// 0x14 : reserved
// 0x18 : Data signal of i_we
//        bit 0  - i_we[0] (Read/Write)
//        others - reserved
// 0x1c : reserved
// 0x20 : Data signal of i_address
//        bit 7~0 - i_address[7:0] (Read/Write)
//        others  - reserved
// 0x24 : reserved
// 0x28 : Data signal of i_write
//        bit 31~0 - i_write[31:0] (Read/Write)
// 0x2c : reserved
// 0x30 : Data signal of o_read
//        bit 31~0 - o_read[31:0] (Read)
// 0x34 : Control signal of o_read
//        bit 0  - o_read_ap_vld (Read/COR)
//        others - reserved
// 0x38 : Data signal of o_error
//        bit 0  - o_error[0] (Read)
//        others - reserved
// 0x3c : Control signal of o_error
//        bit 0  - o_error_ap_vld (Read/COR)
//        others - reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

//------------------------Parameter----------------------
localparam
    ADDR_I_CS_DATA_0      = 6'h10,
    ADDR_I_CS_CTRL        = 6'h14,
    ADDR_I_WE_DATA_0      = 6'h18,
    ADDR_I_WE_CTRL        = 6'h1c,
    ADDR_I_ADDRESS_DATA_0 = 6'h20,
    ADDR_I_ADDRESS_CTRL   = 6'h24,
    ADDR_I_WRITE_DATA_0   = 6'h28,
    ADDR_I_WRITE_CTRL     = 6'h2c,
    ADDR_O_READ_DATA_0    = 6'h30,
    ADDR_O_READ_CTRL      = 6'h34,
    ADDR_O_ERROR_DATA_0   = 6'h38,
    ADDR_O_ERROR_CTRL     = 6'h3c,
    WRIDLE                = 2'd0,
    WRDATA                = 2'd1,
    WRRESP                = 2'd2,
    WRRESET               = 2'd3,
    RDIDLE                = 2'd0,
    RDDATA                = 2'd1,
    RDRESET               = 2'd2,
    ADDR_BITS         = 6;

//------------------------Local signal-------------------
    reg  [1:0]                    wstate = WRRESET;
    reg  [1:0]                    wnext;
    reg  [ADDR_BITS-1:0]          waddr;
    wire [31:0]                   wmask;
    wire                          aw_hs;
    wire                          w_hs;
    reg  [1:0]                    rstate = RDRESET;
    reg  [1:0]                    rnext;
    reg  [31:0]                   rdata;
    wire                          ar_hs;
    wire [ADDR_BITS-1:0]          raddr;
    // internal registers
    reg  [0:0]                    int_i_cs = 'b0;
    reg  [0:0]                    int_i_we = 'b0;
    reg  [7:0]                    int_i_address = 'b0;
    reg  [31:0]                   int_i_write = 'b0;
    reg  [31:0]                   int_o_read = 'b0;
    reg                           int_o_read_ap_vld;
    reg  [0:0]                    int_o_error = 'b0;
    reg                           int_o_error_ap_vld;

//------------------------Instantiation------------------

//------------------------AXI write fsm------------------
assign AWREADY = (wstate == WRIDLE);
assign WREADY  = (wstate == WRDATA);
assign BRESP   = 2'b00;  // OKAY
assign BVALID  = (wstate == WRRESP);
assign wmask   = { {8{WSTRB[3]}}, {8{WSTRB[2]}}, {8{WSTRB[1]}}, {8{WSTRB[0]}} };
assign aw_hs   = AWVALID & AWREADY;
assign w_hs    = WVALID & WREADY;

// wstate
always @(posedge ACLK) begin
    if (ARESET)
        wstate <= WRRESET;
    else if (ACLK_EN)
        wstate <= wnext;
end

// wnext
always @(*) begin
    case (wstate)
        WRIDLE:
            if (AWVALID)
                wnext = WRDATA;
            else
                wnext = WRIDLE;
        WRDATA:
            if (WVALID)
                wnext = WRRESP;
            else
                wnext = WRDATA;
        WRRESP:
            if (BREADY)
                wnext = WRIDLE;
            else
                wnext = WRRESP;
        default:
            wnext = WRIDLE;
    endcase
end

// waddr
always @(posedge ACLK) begin
    if (ACLK_EN) begin
        if (aw_hs)
            waddr <= AWADDR[ADDR_BITS-1:0];
    end
end

//------------------------AXI read fsm-------------------
assign ARREADY = (rstate == RDIDLE);
assign RDATA   = rdata;
assign RRESP   = 2'b00;  // OKAY
assign RVALID  = (rstate == RDDATA);
assign ar_hs   = ARVALID & ARREADY;
assign raddr   = ARADDR[ADDR_BITS-1:0];

// rstate
always @(posedge ACLK) begin
    if (ARESET)
        rstate <= RDRESET;
    else if (ACLK_EN)
        rstate <= rnext;
end

// rnext
always @(*) begin
    case (rstate)
        RDIDLE:
            if (ARVALID)
                rnext = RDDATA;
            else
                rnext = RDIDLE;
        RDDATA:
            if (RREADY & RVALID)
                rnext = RDIDLE;
            else
                rnext = RDDATA;
        default:
            rnext = RDIDLE;
    endcase
end

// rdata
always @(posedge ACLK) begin
    if (ACLK_EN) begin
        if (ar_hs) begin
            rdata <= 1'b0;
            case (raddr)
                ADDR_I_CS_DATA_0: begin
                    rdata <= int_i_cs[0:0];
                end
                ADDR_I_WE_DATA_0: begin
                    rdata <= int_i_we[0:0];
                end
                ADDR_I_ADDRESS_DATA_0: begin
                    rdata <= int_i_address[7:0];
                end
                ADDR_I_WRITE_DATA_0: begin
                    rdata <= int_i_write[31:0];
                end
                ADDR_O_READ_DATA_0: begin
                    rdata <= int_o_read[31:0];
                end
                ADDR_O_READ_CTRL: begin
                    rdata[0] <= int_o_read_ap_vld;
                end
                ADDR_O_ERROR_DATA_0: begin
                    rdata <= int_o_error[0:0];
                end
                ADDR_O_ERROR_CTRL: begin
                    rdata[0] <= int_o_error_ap_vld;
                end
            endcase
        end
    end
end


//------------------------Register logic-----------------
assign i_cs      = int_i_cs;
assign i_we      = int_i_we;
assign i_address = int_i_address;
assign i_write   = int_i_write;
// int_i_cs[0:0]
always @(posedge ACLK) begin
    if (ARESET)
        int_i_cs[0:0] <= 0;
    else if (ACLK_EN) begin
        if (w_hs && waddr == ADDR_I_CS_DATA_0)
            int_i_cs[0:0] <= (WDATA[31:0] & wmask) | (int_i_cs[0:0] & ~wmask);
    end
end

// int_i_we[0:0]
always @(posedge ACLK) begin
    if (ARESET)
        int_i_we[0:0] <= 0;
    else if (ACLK_EN) begin
        if (w_hs && waddr == ADDR_I_WE_DATA_0)
            int_i_we[0:0] <= (WDATA[31:0] & wmask) | (int_i_we[0:0] & ~wmask);
    end
end

// int_i_address[7:0]
always @(posedge ACLK) begin
    if (ARESET)
        int_i_address[7:0] <= 0;
    else if (ACLK_EN) begin
        if (w_hs && waddr == ADDR_I_ADDRESS_DATA_0)
            int_i_address[7:0] <= (WDATA[31:0] & wmask) | (int_i_address[7:0] & ~wmask);
    end
end

// int_i_write[31:0]
always @(posedge ACLK) begin
    if (ARESET)
        int_i_write[31:0] <= 0;
    else if (ACLK_EN) begin
        if (w_hs && waddr == ADDR_I_WRITE_DATA_0)
            int_i_write[31:0] <= (WDATA[31:0] & wmask) | (int_i_write[31:0] & ~wmask);
    end
end

// int_o_read
always @(posedge ACLK) begin
    if (ARESET)
        int_o_read <= 0;
    else if (ACLK_EN) begin
        if (o_read_ap_vld)
            int_o_read <= o_read;
    end
end

// int_o_read_ap_vld
always @(posedge ACLK) begin
    if (ARESET)
        int_o_read_ap_vld <= 1'b0;
    else if (ACLK_EN) begin
        if (o_read_ap_vld)
            int_o_read_ap_vld <= 1'b1;
        else if (ar_hs && raddr == ADDR_O_READ_CTRL)
            int_o_read_ap_vld <= 1'b0; // clear on read
    end
end

// int_o_error
always @(posedge ACLK) begin
    if (ARESET)
        int_o_error <= 0;
    else if (ACLK_EN) begin
        if (o_error_ap_vld)
            int_o_error <= o_error;
    end
end

// int_o_error_ap_vld
always @(posedge ACLK) begin
    if (ARESET)
        int_o_error_ap_vld <= 1'b0;
    else if (ACLK_EN) begin
        if (o_error_ap_vld)
            int_o_error_ap_vld <= 1'b1;
        else if (ar_hs && raddr == ADDR_O_ERROR_CTRL)
            int_o_error_ap_vld <= 1'b0; // clear on read
    end
end


//------------------------Memory logic-------------------

endmodule
