// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// AXILiteS
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of i_cs
//        bit 0  - i_cs[0] (Read/Write)
//        others - reserved
// 0x14 : reserved
// 0x18 : Data signal of i_we
//        bit 0  - i_we[0] (Read/Write)
//        others - reserved
// 0x1c : reserved
// 0x20 : Data signal of i_address
//        bit 7~0 - i_address[7:0] (Read/Write)
//        others  - reserved
// 0x24 : reserved
// 0x28 : Data signal of i_write
//        bit 31~0 - i_write[31:0] (Read/Write)
// 0x2c : reserved
// 0x30 : Data signal of o_read
//        bit 31~0 - o_read[31:0] (Read)
// 0x34 : Control signal of o_read
//        bit 0  - o_read_ap_vld (Read/COR)
//        others - reserved
// 0x38 : Data signal of o_error
//        bit 0  - o_error[0] (Read)
//        others - reserved
// 0x3c : Control signal of o_error
//        bit 0  - o_error_ap_vld (Read/COR)
//        others - reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XSHA1_CONTROL_AXILITES_ADDR_I_CS_DATA      0x10
#define XSHA1_CONTROL_AXILITES_BITS_I_CS_DATA      1
#define XSHA1_CONTROL_AXILITES_ADDR_I_WE_DATA      0x18
#define XSHA1_CONTROL_AXILITES_BITS_I_WE_DATA      1
#define XSHA1_CONTROL_AXILITES_ADDR_I_ADDRESS_DATA 0x20
#define XSHA1_CONTROL_AXILITES_BITS_I_ADDRESS_DATA 8
#define XSHA1_CONTROL_AXILITES_ADDR_I_WRITE_DATA   0x28
#define XSHA1_CONTROL_AXILITES_BITS_I_WRITE_DATA   32
#define XSHA1_CONTROL_AXILITES_ADDR_O_READ_DATA    0x30
#define XSHA1_CONTROL_AXILITES_BITS_O_READ_DATA    32
#define XSHA1_CONTROL_AXILITES_ADDR_O_READ_CTRL    0x34
#define XSHA1_CONTROL_AXILITES_ADDR_O_ERROR_DATA   0x38
#define XSHA1_CONTROL_AXILITES_BITS_O_ERROR_DATA   1
#define XSHA1_CONTROL_AXILITES_ADDR_O_ERROR_CTRL   0x3c

