// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xsha1_control.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XSha1_control_CfgInitialize(XSha1_control *InstancePtr, XSha1_control_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XSha1_control_Set_i_cs(XSha1_control *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSha1_control_WriteReg(InstancePtr->Axilites_BaseAddress, XSHA1_CONTROL_AXILITES_ADDR_I_CS_DATA, Data);
}

u32 XSha1_control_Get_i_cs(XSha1_control *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSha1_control_ReadReg(InstancePtr->Axilites_BaseAddress, XSHA1_CONTROL_AXILITES_ADDR_I_CS_DATA);
    return Data;
}

void XSha1_control_Set_i_we(XSha1_control *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSha1_control_WriteReg(InstancePtr->Axilites_BaseAddress, XSHA1_CONTROL_AXILITES_ADDR_I_WE_DATA, Data);
}

u32 XSha1_control_Get_i_we(XSha1_control *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSha1_control_ReadReg(InstancePtr->Axilites_BaseAddress, XSHA1_CONTROL_AXILITES_ADDR_I_WE_DATA);
    return Data;
}

void XSha1_control_Set_i_address(XSha1_control *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSha1_control_WriteReg(InstancePtr->Axilites_BaseAddress, XSHA1_CONTROL_AXILITES_ADDR_I_ADDRESS_DATA, Data);
}

u32 XSha1_control_Get_i_address(XSha1_control *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSha1_control_ReadReg(InstancePtr->Axilites_BaseAddress, XSHA1_CONTROL_AXILITES_ADDR_I_ADDRESS_DATA);
    return Data;
}

void XSha1_control_Set_i_write(XSha1_control *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSha1_control_WriteReg(InstancePtr->Axilites_BaseAddress, XSHA1_CONTROL_AXILITES_ADDR_I_WRITE_DATA, Data);
}

u32 XSha1_control_Get_i_write(XSha1_control *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSha1_control_ReadReg(InstancePtr->Axilites_BaseAddress, XSHA1_CONTROL_AXILITES_ADDR_I_WRITE_DATA);
    return Data;
}

u32 XSha1_control_Get_o_read(XSha1_control *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSha1_control_ReadReg(InstancePtr->Axilites_BaseAddress, XSHA1_CONTROL_AXILITES_ADDR_O_READ_DATA);
    return Data;
}

u32 XSha1_control_Get_o_read_vld(XSha1_control *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSha1_control_ReadReg(InstancePtr->Axilites_BaseAddress, XSHA1_CONTROL_AXILITES_ADDR_O_READ_CTRL);
    return Data & 0x1;
}

u32 XSha1_control_Get_o_error(XSha1_control *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSha1_control_ReadReg(InstancePtr->Axilites_BaseAddress, XSHA1_CONTROL_AXILITES_ADDR_O_ERROR_DATA);
    return Data;
}

u32 XSha1_control_Get_o_error_vld(XSha1_control *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSha1_control_ReadReg(InstancePtr->Axilites_BaseAddress, XSHA1_CONTROL_AXILITES_ADDR_O_ERROR_CTRL);
    return Data & 0x1;
}

