// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XSHA1_CONTROL_H
#define XSHA1_CONTROL_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xsha1_control_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XSha1_control_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XSha1_control;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XSha1_control_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XSha1_control_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XSha1_control_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XSha1_control_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XSha1_control_Initialize(XSha1_control *InstancePtr, u16 DeviceId);
XSha1_control_Config* XSha1_control_LookupConfig(u16 DeviceId);
int XSha1_control_CfgInitialize(XSha1_control *InstancePtr, XSha1_control_Config *ConfigPtr);
#else
int XSha1_control_Initialize(XSha1_control *InstancePtr, const char* InstanceName);
int XSha1_control_Release(XSha1_control *InstancePtr);
#endif


void XSha1_control_Set_i_cs(XSha1_control *InstancePtr, u32 Data);
u32 XSha1_control_Get_i_cs(XSha1_control *InstancePtr);
void XSha1_control_Set_i_we(XSha1_control *InstancePtr, u32 Data);
u32 XSha1_control_Get_i_we(XSha1_control *InstancePtr);
void XSha1_control_Set_i_address(XSha1_control *InstancePtr, u32 Data);
u32 XSha1_control_Get_i_address(XSha1_control *InstancePtr);
void XSha1_control_Set_i_write(XSha1_control *InstancePtr, u32 Data);
u32 XSha1_control_Get_i_write(XSha1_control *InstancePtr);
u32 XSha1_control_Get_o_read(XSha1_control *InstancePtr);
u32 XSha1_control_Get_o_read_vld(XSha1_control *InstancePtr);
u32 XSha1_control_Get_o_error(XSha1_control *InstancePtr);
u32 XSha1_control_Get_o_error_vld(XSha1_control *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
