// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xsha1_control.h"

extern XSha1_control_Config XSha1_control_ConfigTable[];

XSha1_control_Config *XSha1_control_LookupConfig(u16 DeviceId) {
	XSha1_control_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XSHA1_CONTROL_NUM_INSTANCES; Index++) {
		if (XSha1_control_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XSha1_control_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XSha1_control_Initialize(XSha1_control *InstancePtr, u16 DeviceId) {
	XSha1_control_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XSha1_control_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XSha1_control_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

